// lib/firebase_options.dart — generated by flutterfire configure
// DO NOT edit manually. Re-run `flutterfire configure` to regenerate.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8mNbSVz3uEiRj-lVR8P3hREHMNl8GxW4',
    appId: '1:953302924189:web:069f84de9dddf8c6910d74',
    messagingSenderId: '953302924189',
    projectId: 'patamjengo',
    authDomain: 'patamjengo.firebaseapp.com',
    storageBucket: 'patamjengo.firebasestorage.app',
    measurementId: 'G-3713QW0R36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCbpzMWyLLbD76Acj9ETX7XXtWk3wdvcY',
    appId: '1:953302924189:android:6e0d9c9dc50e1b68910d74',
    messagingSenderId: '953302924189',
    projectId: 'patamjengo',
    storageBucket: 'patamjengo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz7IqoPs7BT1knRTu7ikTRlGL5b0RSWcU',
    appId: '1:953302924189:ios:cd9990aa6524bc93910d74',
    messagingSenderId: '953302924189',
    projectId: 'patamjengo',
    storageBucket: 'patamjengo.firebasestorage.app',
    iosBundleId: 'com.patamjengo.app',
  );
}
